#ifndef SPI_CONFIG_H
#define SPI_CONFIG_H

#define SPI_MODE SPI_MASTER

#define SPI_DATA_ORDER SPI_DATA_ORDER_LSB

#define SPI_POLARITY_MODE SPI_POLARITY_FALLING

#define SPI_PHASE_MODE SPI_SAMPLE_LEADING

#define SPI_PRESCALER SPI_PRESCALER_4

#endif