#ifndef USART_CONFIG_H
#define USART_CONFIG_H

#define USART_MODE USART_ASYNCHRONOUS

#define USART_DATA_BITS USART_DATA_8BIT

#define USART_PARITY USART_NO_PARITY

#define USART_STOP_BITS USART_STOP_1BIT

#define USART_SPEED USART_NORMAL_SPEED

#define USART_BAUD_RATE USART_BAUD_9600

#define USART_CLOCK_MODE USART_RISING_EDGE

#endif