#ifndef TIMER1_CONFIG_H
#define TIMER1_CONFIG_H

#define TIMER1_MODE TIMER1_FREQUENCY_PHASE_CORRECT

#define TIMER1_PRESCALER TIMER1_PRESCALER_8

#define TIMER1_TOP TOP_ICR

#define OC1A_MODE OC1A_NONINVERTING

#define OC1B_MODE OC1B_TOGGLE

#endif