#ifndef ADC_CONFIG_H
#define ADC_CONFIG_H

#define ADC_ADJUST RIGHT_ADJUST

#define ADC_MODE SINGLE_CONVERSION

#define PRESCALER 128

#define REFERENCE AVCC

#define AUTO_TRIGGER_MODE FREE_RUNNING

#endif