#ifndef ADC_CONFIG_H
#define ADC_CONFIG_H

#define ADC_ADJUST RIGHT_ADJUST

#define ADC_MODE SINGLE_CONVERSION

#define PRESCALER 128

#define REFERENCE AREF

#define AREF_VOLTAGE 3.0f

#define VCC_VOLTAGE 5.0f

#define VREF_VOLTAGE 2.56f

#define AUTO_TRIGGER_MODE FREE_RUNNING

#endif